### ISSUE TITLE
The end of a public review period is not present on the detail page

### ISSUE THREAD

**Issue by KristofVDB1** [Informatievlaanderen/OSLO-Standaardenregister#17]
**Describe the bug**
Some older standards used to have a key called **Einde publieke review**. This is no longer present in the updated config file: https://github.com/Informatievlaanderen/OSLOthema-perceel/blob/standaardenregister/ap-percelen-config.json#L78C1-L79C1

**To Reproduce**
https://data.vlaanderen.be/standaarden/erkende-standaard/applicatieprofiel-dcat-ap-vl-2.0.html

**Expected behavior**
Contain the data from the end of a public review period

**Screenshots**
<img width="1160" alt="Screenshot 2024-05-22 at 13 49 28" src="https://github.com/Informatievlaanderen/OSLO-Standaardenregister/assets/28532087/cf4be38c-135a-4038-bd8a-d1aa9957eb45">

**Comment by jitsedc** [comment]
If possible it would be good to also capture the date for the start of a public review period too. This way this info is easily retrievable. Currently this info is only captured indirectly via the publication date of a specific version (in the URL) or via the reports of the working group (not easy to find and not always made publicly available).

**Comment by KristofVDB1** [comment]
After a meeting with @bertvannuffelen, we decided to extend the config with a total of three extra dates:
* Date for the start of a public review
* Date for the end of a public review
* Date for the end of a publication (new version of the publication, deprecated,...)

**Comment by KristofVDB1** [comment]
@jitsedc This has been added! Will close this issue for now. Feel free to reopen this if something related to this pops up again
